# Generated by Django 5.0.4 on 2024-05-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_question_answer_quizzes_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_input',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
