# Generated by Django 5.0.4 on 2024-05-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer_answer_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_input',
        ),
    ]
