# Generated by Django 5.0.4 on 2024-05-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_answer_answer_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_input',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
