# Generated by Django 5.0.4 on 2024-05-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_answer_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexplainer',
            name='_inputanswer',
            field=models.TextField(null=True),
        ),
    ]
