# Generated by Django 5.0.4 on 2024-05-04 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_codeexplainer_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeexplainer',
            name='quiz',
        ),
        migrations.AddField(
            model_name='codeexplainer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_explainer', to='api.question'),
        ),
    ]
