# Generated by Django 5.0.4 on 2024-05-04 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_question_codeexplainer__question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexplainer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_explainer', to='api.quizzes'),
        ),
    ]
